<a href="https://colab.research.google.com/github/KarnamVishalAI/100day-AI-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr = np.array([1,2,3,4])
arr1 = np.array(42)
print(arr)
print(np.__version__)
print(type(arr))
print(arr1)

[1 2 3 4]
2.0.2
<class 'numpy.ndarray'>
42


In [11]:
import numpy as np
a = np.array([[1,2,5],[3,4,6]])
b = np.array([[[1,2,6],[3,4,9],[5,6,1],[7,8,7]]])# these are 2D and 3D arrays
print(a)
print(b)
print(b.ndim)

[[1 2 5]
 [3 4 6]]
[[[1 2 6]
  [3 4 9]
  [5 6 1]
  [7 8 7]]]
3


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
# indexinf arrays
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2])
print(arr[0]+ arr[1])

3
3


In [22]:
#indexing 2d and 3D arrays
import numpy as np
a = np.array([[1,2,5],[3,4,6]])#2D array
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])#3D array
print(a[0,2])
print(a[1,-1])
print(b[1,1,2])
print(b)

5
6
12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
#slicing
import numpy as np
arr = np.array([1,2,3,4])
a = np.array([[1,2,5],[3,4,6]])#2D array

print(arr[0:])# 1D slicing

print(a[1, 0:2])#2D slicing
print(a[0:2, 2])

print(arr[0:4:2])#used step to skip

[1 2 3 4]
[3 4]
[5 6]
[1 3]
