<a href="https://colab.research.google.com/github/KarnamVishalAI/100day-AI-journey/blob/main/Student_Performance_Analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

students = np.array(["Aarav", "Meera", "Rohan", "Ananya", "Vikram"])
subjects = np.array(["Maths", "Science", "English"])

marks = np.array([
    [85, 78, 92],
    [74, 88, 81],
    [90, 91, 89],
    [65, 70, 72],
    [88, 84, 90]
])

print(marks)
print("------------------------------")

student_avg = np.mean(marks, axis=1)
for i in range(len(students)):
    print(students[i], student_avg[i])

print("------------------------------")

subject_avg = np.mean(marks, axis=0)
for i in range(len(subjects)):
    print(subjects[i], subject_avg[i])

print("------------------------------")

top_index = np.argmax(student_avg)
print(students[top_index], student_avg[top_index])

print("------------------------------")

def assign_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    elif avg >= 70:
        return "C"
    else:
        return "D"

for i in range(len(students)):
    print(students[i], assign_grade(student_avg[i]))

print("------------------------------")

high_scorers = students[student_avg > 85]
print(high_scorers)


[[85 78 92]
 [74 88 81]
 [90 91 89]
 [65 70 72]
 [88 84 90]]
------------------------------
Aarav 85.0
Meera 81.0
Rohan 90.0
Ananya 69.0
Vikram 87.33333333333333
------------------------------
Maths 80.4
Science 82.2
English 84.8
------------------------------
Rohan 90.0
------------------------------
Aarav B
Meera B
Rohan A
Ananya D
Vikram B
------------------------------
['Rohan' 'Vikram']
